<?php

return [
    'modules' => [
        'dashboard' => 'Dashboard',
        'rental_trips' => 'Rental Trips',
        'cars' => 'Cars',
        'customers' => 'Customers',
        'payments' => 'Payments',
        'expenses' => 'Expenses',
        'vehicle_maintenance' => 'Vehicle Maintenance',
        'agreements' => 'Agreements',
        'gps_logs' => 'DAGPS KM Logs',
        'users_manage' => 'Users & Roles',
        'permissions_manage' => 'Permissions',
    ],

    'defaults' => [
        'admin' => [
            'dashboard' => true,
            'rental_trips' => true,
            'cars' => true,
            'customers' => true,
            'payments' => true,
            'expenses' => true,
            'vehicle_maintenance' => true,
            'agreements' => true,
            'gps_logs' => true,
            'users_manage' => true,
            'permissions_manage' => true,
        ],
        'customer' => [
            'dashboard' => true,
            'rental_trips' => false,
            'cars' => false,
            'customers' => false,
            'payments' => false,
            'expenses' => false,
            'vehicle_maintenance' => false,
            'agreements' => false,
            'gps_logs' => false,
            'users_manage' => false,
            'permissions_manage' => false,
        ],
        'partner' => [
            'dashboard' => false,
            'rental_trips' => true,
            'cars' => false,
            'customers' => false,
            'payments' => false,
            'expenses' => false,
            'vehicle_maintenance' => false,
            'agreements' => false,
            'gps_logs' => false,
            'users_manage' => false,
            'permissions_manage' => false,
        ],
    ],
];
